### ISSUE TITLE
Entire model needs review for building errors

### ISSUE THREAD

**Issue by marklinnane** [marklinnane/BCD-Interactive-City-Scale-Models#83]
**Review materials**
- 1km tile with buildings and terrain
- KML or other reference to Google maps
- Instructions for reviewers

**Tasks**
- [x] Solve iteration
- [x] Batch output tiles
- [x] Build KML conversion
       - [ ] Break and review building extrusion
- [x] Output KML files based on 1km tiles without terrain
- [x] Do simple terrain
- [x] Assess KML for suitability
- [x] Make instructions
- [x] Trial validation - prioritize first tile for printer
- [x] Make list of validators
- [x] Sign off
- [ ] Check validation materials
- [ ] Check rivers
- [ ] Check bridges
- [ ] Check railways
- [ ] Check snipped corners

**Comment by marklinnane** [comment]
**Review materials**
- 500m tile with buildings and terrain
- KML or other reference to Google maps

**Tasks**
- [ ] Batch output tiles
- [ ] Assess KML for suitability
- [ ] Creat Google maps references
